apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service2
  name: service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service2
    spec:
      containers:
        - image: public.ecr.aws/n8u7z3z1/service2:service2
          name: service2
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 4000
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    run: service2
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: service2
  type: NodePort
